// GENERATED by scripts/harvest_reddit_thumbs.py — do not hand-edit.
// Rendered from the real Reddit templates in the ADAM 2026 Figma file, so
// the picker shows Reddit artwork for Reddit ad types. Rerun the script
// after a template change.
export const REDDIT_STYLE_THUMBS: Record<string, string> = {
  "App Notification": "/style-previews/reddit/app-notification.jpg",
  "Button": "/style-previews/reddit/button.jpg",
  "Graphic with Text": "/style-previews/reddit/graphic-with-text.jpg",
  "Icon": "/style-previews/reddit/icon.jpg",
  "Logo": "/style-previews/reddit/logo.jpg",
  "Meme": "/style-previews/reddit/meme.jpg",
  "Note": "/style-previews/reddit/note.jpg",
  "Notification": "/style-previews/reddit/notification.jpg",
  "Person Only": "/style-previews/reddit/person-only.jpg",
  "Person with Text": "/style-previews/reddit/person-with-text.jpg",
  "Pie Chart": "/style-previews/reddit/pie-chart.jpg",
  "Search": "/style-previews/reddit/search.jpg",
  "Search and Checkbox": "/style-previews/reddit/search-and-checkbox.jpg",
  "Split Screen": "/style-previews/reddit/split-screen.jpg",
  "Testimonial": "/style-previews/reddit/testimonial.jpg",
  "Text Only": "/style-previews/reddit/text-only.jpg",
  "Text with Icons": "/style-previews/reddit/text-with-icons.jpg",
  "Twitter": "/style-previews/reddit/twitter.jpg",
  "Us vs Them": "/style-previews/reddit/us-vs-them.jpg",
  "Venn Diagram": "/style-previews/reddit/venn-diagram.jpg",
};
